language: node_js
node_js:
  - "iojs"
  - "7"

deploy:
  provider: heroku
  api_key: "amSKiaQZAL/OT7jASvNVEypmhoupITiQhoOWWr5LljBNs2TqnIslcalu4cbMBYNKU1mQLVjooQ1h1TICUjeXWlQ6WT8IhUYGEpU2NTIbAImZtUwZhTbx6SiYMxtnqXqkA4jg2Kshx7Cgdrj4efr+2maLFCEzYfUlHih3Bc4h2ZAYLkqL8lQMzznPwVGX8Dhwp2NktoiGWUfuXG7YnSdM4CVxCsZ94x9aKHrtnlzz3oMMtwys4Dyj6s7zlUb36eNTVZsIazpJgNV6lQZjC4kHltFFbayLRYt3Pp3ftIsqZpBiPEQhTfGGVYCsOguFFTecH3hxD7kQwvvQAABQ/H61DjbZt9fEYSv33HBuEAa7+hw9Q8V0mQV5vh1LCKjcGpYCVJbFjA6upkJgUiLrqSHNDNkmIrI0DhBI4kalpvJTxEz0ttHtWOgawNXVjSKSe1sskiMRgCNtHZmSJoucVPntgzgz6woslY4mqydkZqV1WxIS9Fy/6dW9UPecpjeqV98sOO5qkNiDopSqQehesHdAT72QcAACCH/+m1mWcGfSgtnQXuuNaSWNh6vvtko0YmMACZKd/No0aY1zFG7nU+UjmUPdyjekDX0cTJXCM7/hFeGoJHRLeBzGy6RloYX3XAkjok72FaJ9SZvYNGJe6XWB/Y2aig6tyEpSUhQ14j0c8Hs="
  app:
    develop:  the-circle-account